version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: courses-postgres
    restart: always
    environment:
      POSTGRES_DB: courses_db
      POSTGRES_USER: courses_user
      POSTGRES_PASSWORD: courses_pass
    ports:
      - "5432:5432"
    volumes:
      - courses_data:/var/lib/postgresql/data

#  finance-api:
#    build: .
#    container_name: finance-api
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance_db
#      SPRING_DATASOURCE_USERNAME: finance_user
#      SPRING_DATASOURCE_PASSWORD: finance_pass

volumes:
  courses_data: